### PR TITLE
fix(npm scripts): fix path in commitizen config

### PR DESCRIPTION
**Pull request by zautumnz**
Fixes /app/node_modules to just /node_modules

## Description
Fixes issue mentioned in #3 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue
#3 

## How Has This Been Tested?
This commit is the test.

## Screenshots (if appropriate):
image

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Great catch!
Can you make a similar PR to https://github.com/lirantal/create-node-lib/blob/master/template/package.json#L105 and https://github.com/lirantal/create-node-lib/blob/master/package.json#L126 which is the generator I use for my projects ?

**Review by lirantal — APPROVED** [review]

**Comment by zautumnz** [comment]
Sure thing! https://github.com/lirantal/create-node-lib/pull/7

**Comment by lirantal** [comment]
thanks!

**Pull request merged**
